name: Self-Hosted Runner Workflow

on:
  push:
    branches:
      - main
# on:
#   workflow_dispatch:

jobs:
  analyze:
    name: Analyze
    runs-on: self-hosted
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'rust' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check For Heart Beat
      run: |
          echo "Running on a self-hosted runner"
          uname -a
          echo "Job complete"
    