name: Security test Suite for Containers (K8s & Containerization)

on:
  push:
    branches:
      - main
# on:
#   workflow_dispatch:

jobs:
  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'typescript']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  self-hosted-job:
    name: Self-Hosted Job
    runs-on: self-hosted
    needs: codeql

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run a script on Self-Hosted Runner
        run: |
          echo "Running on self-hosted runner"