name: Security test Suite for Containers (K8s & Containerization)

on:
  push:
    branches:
      - main
# on:
#   workflow_dispatch:

jobs:
  analyze:
    name: Analyze
    runs-on: self-hosted
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'TypeScript']
    
    steps:
    - name: Checking For Agent Heart Beat
      run: |
          echo "Running on a self-hosted runner"
          uname -a
          echo "I am Alive"

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}
        database: ./codeql-databases
    
    - name: Autobuild
      uses: github/codeql-action/autobuild@v2
    
    - name: Run CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        database: ./codeql-databases


    
